### ISSUE TITLE
Could you support dotnet core please?

### ISSUE THREAD

**Issue by RunkyZhang** [zzzprojects/Bulk-Operations#1]

**Comment by zzzprojects** [comment]
Thank you for your suggestion.

That is currently in our plan to re-write all the library and at the same time supporting dotnet core.

However, we still have no starting date since there is some other tasks we want to complete before re-writing this library.

**Comment by AR1ES** [comment]
Is there any timings?

**Comment by JonathanMagnan** [comment]
Hello @AR1ES ,

I have some good news concerning this request.

This request was started last month. We will first deliver a version for Entity Framework Extensions for .NET Core (which use this library under the hood) then we will complete the support for this library.

I have added a task to contact you at the beginning of next month to give a status if that has not been completed yet.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello Guys,

Sorry for the long delay, it seems I have forgotten to answer this issue when .NET Core support has been added.

The library should support .NET Standard 2.0, it currently works only with a few providers (SQL Server, SQL Azure, Postgre), but we are currently adding more.

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment]
Hi Jonathan, 

Thanks for the update, could you please let me know a rough ETA for the MySql provider in .NET Core.

Thanks 

Mike

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

I will try to check if we can push it for next Monday.

So more information will be provided at the start of next week about the ETA.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

It seems we forget to update this issue.

The support to `MySql.Data` for .NET Core has been added a few month ago.

If you test it, please let me know about your result.

Best Regards,

Jonathan
