### ISSUE TITLE
how to get Identity Value  for each iteration bulk insert

### ISSUE THREAD

**Issue by musti276** [zzzprojects/Bulk-Operations#11]
List< IletisimLog> bulkInsertIletisimLog = new List<IletisimLog>();
            //there are 1000 values in the array of paramaters
            foreach (var kId in paramaters)
            {     
                var iletisimLogInsert = new IletisimLog()
                {
                    KullaniciID = kId.KullaniciId,
                    EklendigiTarih = DateTime.Now,
                    GonderildigiTarih = DateTime.Now,
                    BilgilendirmeTurID = bilgilendirmeturId,
                };
                bulkInsertIletisimLog.Add(iletisimLogInsert);

            }
            _iLetisimLogService.BulkInsertRange(bulkInsertIletisimLog);
       

       
//There are 1000 records registered in the database. How to get the primary key value for each record

**Comment by JonathanMagnan** [comment]
Hello @musti276 ,

To output record, you will need to specify a mapping. Here is an example using lambda expression

```csharp
var bulk= new BulkOperation<IletisimLog>(connection);
bulk.DestinationTableName = "IletisimLogs";

// Column Input Expression
bulk.ColumnInputExpression = c => new { c.KullaniciID, c.EklendigiTarih, c.GonderildigiTarih, c.BilgilendirmeTurID };

// Column Output Expression
bulk.ColumnOutputExpression = c => c.IletisimLogID;

bulk.BulkInsert(bulkInsertIletisimLog);
```

Let me know if that example helped you or if you need more information

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: No answer, feel free to re-open if you still have questions.
