### ISSUE TITLE
Is running in Mono?

### ISSUE THREAD

**Issue by smerps** [zzzprojects/Bulk-Operations#13]
Is running in Mono?

**Comment by JonathanMagnan** [comment]
Hello @smerps ,

We will very soon release a version supporting .NET Standard 2.x but we have no plan to support Mono.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @smerps ,

I will close this request since we have no plan to support Mono.

Best Regards,

Jonathan
