### ISSUE TITLE
Several Bulk problems

### ISSUE THREAD

**Issue by Nuklon** [zzzprojects/Bulk-Operations#15]
I'm using connection.BeginTransaction() and then the ...Bulk methods on the transaction, but none of them are working. Without a transaction it's the same.

BulkMerge has this problem:
The DestinationTableName cannot be null or empty. You must specify a valid DestinationTableName.'
     transaction.BulkMerge(items, x => x.Name, x => x.Type, x => x.Information);

BulkInsert on the other hand has this problem (without the selectors, otherwise it's the same message as BulkMerge):
System.Exception: 'Error: 0013: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com'

-->

   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
   at Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbTransaction transaction, String mapperKey, T item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbTransaction transaction, T item, Func`2[] selectors)

It doesn't matter if I use the DapperPlusManager.Entity<...>().Map methods or not, it never works. Just Dapper works fine, and also all other Dapper helpers on NuGet.

**Comment by JonathanMagnan** [comment]
Hello @Nuklon ,

What is the type of `items`. By default when not mapped, the library try to guess the name from the type which doesn't seem to be supported.

Do you think you could provide us a small example to let us better investigate this issue? info@zzzzprojects.com

Best Regards,

Jonathan

**Comment by Nuklon** [comment]
Hi @JonathanMagnan 

I use Dapper FastCrud for auto mapping, it's exactly like this:

    /// <summary>
    /// A class which represents the Item table.
    /// </summary>
	[Table("Item")]
	public partial class Item
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int Id { get; set; }
	    public virtual string Name { get; set; }
	    public virtual short Type { get; set; }
	    public virtual string Information { get; set; }
	}

This is all 1:1 like this in SQL Server 2014.
Dapper, FastCrud and Dapper Contrib all work fine, just ZZZ not.
If I remove the selectors from BulkMerge I get the same exception as BulkInsert.
But given how limited the stacktrace is, I'm not sure how much use that is.

**Comment by JonathanMagnan** [comment]
Hello @Nuklon ,

My mistake, all information in your first post was here.

This line is invalid: `transaction.BulkMerge(items, x => x.Name, x => x.Type, x => x.Information);`

Additional parameter are not `selectors` for field but `selectors` for additional entity/list to merge.

By example: `transaction.BulkMerge(items, x => x.Childs);`

## AutoMapping
If you want to use AutoMapping, you can make this example work with this line:

```csharp
transaction.BulkMerge(items);
```

## CustomMapping
If you want to specify some custom mapping, here is an example:

```csharp
DapperPlusManager.Entity<Item>("mapperKey_001")
    .Table("Item")
    .Map(x => new {x.Name, x.Type});
	
// ...code...
transaction.BulkMerge("mapperKey_001", items);
```

let me know if that successfully answer to your question.

Best Regards,

Jonathan

**Comment by Nuklon** [comment]
Hi Jonathan,

No problem 👍 
I already tried without the selectors (I read it when you posted that) and then the Oops! 0013 exception is also thrown.

**Comment by JonathanMagnan** [comment]
Hello @Nuklon ,

Thank you for this additional information.

Do I'm wrong if I say you currently use an hacked license name & key with our library?

Best Regards,

Jonathan

**Comment by Nuklon** [comment]
Hi Jonathan,

No, I'm just using the trial version from NuGet.

**Comment by JonathanMagnan** [comment]
That's strange,

Do you think you could provide us an example project that do this error?

I don't think I will be able to replicate it.

It work flawless on our side:

```csharp
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlClient;
using System.Windows.Forms;
using Z.Dapper.Plus;

namespace Z.Lab
{
    public partial class Form_Request_General : Form
    {
        public Form_Request_General()
        {
            InitializeComponent();

            var list = new List<Item>();

            for (var i = 0; i < 5; i++)
            {
                list.Add(new Item {Type = (short) i, Name = "Z_" + i, Information = "Z__" + i});
            }

            for (int i = 0; i < 100; i++)
            {
                using (var conn = new SqlConnection(My.AppConfig.ConnectionStrings.DapperPlusConnection))
                {
                    conn.Open();

                    using (var trans = conn.BeginTransaction())
                    {
                        trans.BulkInsert(list);
                        trans.Commit();
                    }
                }
            }
        }

        [Table("Item")]
        public class Item
        {
            [Key]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public virtual int Id { get; set; }

            public virtual string Name { get; set; }
            public virtual short Type { get; set; }
            public virtual string Information { get; set; }
        }
    }
}
```

**Comment by Nuklon** [comment]
I'll see if I can create a small test project for this, it's currently part of something much larger. Probably early next week, thanks for the help 👍

**Comment by Nuklon** [comment]
@JonathanMagnan 
I've been trying out some more and I've now added manual mapping for all properties through DapperPlusManager.Entity, and it now seems to be working (I tried it several times). 
Thanks for the help again 🏆
