### ISSUE TITLE
Error during bulk insert

### ISSUE THREAD

**Issue by eugene-chehovskoy** [zzzprojects/Bulk-Operations#16]
Hi,

I'm getting an error during bulk insert on .NET Core 2.0 and library version 2.13.7:
> The type initializer for '' threw an exception.

Inner exception:
> Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.

Code:
```
using (var bulk = new BulkOperation<Person>(connection))
{
	bulk.Transaction = transaction;
	bulk.DestinationTableName = "dbo.Persons";
	bulk.BatchSize = _importExportOptions.Import.BatchSize;
	bulk.BatchTimeout = _importExportOptions.Import.BatchTimeout;
	bulk.CaseSensitive = CaseSensitiveType.Insensitive;

	bulk.BulkInsert(newPersons);
}
```

**Comment by JonathanMagnan** [comment]
Hello @eugene-chehovskoy ,

Did we miss to add a dependencies or this issue was on your side?

Best Regards,

Jonathan

**Comment by eugene-chehovskoy** [comment]
Sorry, accidentally closed the issue. Problem still exists.

**Comment by JonathanMagnan** [comment]
Hello @eugene-chehovskoy ,

The v2.13.8 has been released.

For an unknown reason, our obfuscator was modifying the string which is not compatible with .NET Core. We normally always have this setting turned `off`.

Let me know if the new version is working correctly.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @eugene-chehovskoy ,

I will close this issue since the fix has been released.

Best Regards,

Jonathan
