### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by observer1** [zzzprojects/Bulk-Operations#17]
Hi
Whats the right way to use a transaction that rollbacks the whole bulkinsert, we have tried a few combinations but always some data gets persisted.
Can you provide some example code?

Thanks for your help

**Comment by JonathanMagnan** [comment]
Hello @observer1 ,

The following options should handle your scenario `operation.InternalTransaction = InternalTransactionType.ByOperation;`

However, we recommend you to control yourself the transaction.

Let me know if you try the option if that worked.

Best Regards,

Jonathan

**Comment by observer1** [comment]
It seems to be working know I'm closing this
