### ISSUE TITLE
Bulk insert never ends

### ISSUE THREAD

**Issue by observer1** [zzzprojects/Bulk-Operations#18]
Hi
Can you help us with this issue?
We developed an application that copies data between 2 servers using a datareader and when we tried in a testing environment the bulk insert never ends.
Is there some known issue or a hint to this?

Thanks for your help

**Comment by JonathanMagnan** [comment]
Hello @observer1 ,

No, there is no known issue like this one.

I suspect there is something that's currently blocking the bulk operations.

- Could you try in your testing environment to copy only a small amount of row and increase it this amount if that works?
- Could you try to check if something might block the current bulk operations?

Best Regards,

Jonathan

**Comment by observer1** [comment]
It hangs even with one row
I changed the batchsize to 10 and it hangs on 10

I'll try to see what can block this, but I have no clue where to search,
I'm not so good on sql server

2018-01-11 17:33 GMT-06:00 Jonathan Magnan <notifications@github.com>:

**Comment by JonathanMagnan** [comment]
Do you think you could provide us a project or something that we could investigate?

So far, your problem doesn't look related to our library but if we have a simple project that we could check, we will be happy to take some time on it.

You can send it here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by observer1** [comment]
It was a permissions thing
I supposed this would rise an exception...
Thanks for your help I'm closing now

**Comment by JonathanMagnan** [comment]
Hello @observer1 ,

Thank you for letting us known.

Yes, that's weird that no exception was thrown. 

Best Regards,

Jonathan
