### ISSUE TITLE
Performance difference with BulkOperation Insert and Context.BulkInsert

### ISSUE THREAD

**Issue by keerthankumarCSnet** [zzzprojects/Bulk-Operations#19]
We are using ZZZ EntityFramework Core extension version 2.0.10. I tried using couple of option for performing the bulk Insert operation:

Option1:

   var conn = context.Database.GetDbConnection();
   var bulk = new BulkOperation(conn);
   bulk.BulkInsert(result);

The entity on which this works has an Id column set as PrimaryKey. This operation takes about 2 minutes to process to 200000 records.

Option2:

  context.BulkInsert<T>(result, options =>
                        {
                           options.SqlBulkCopyOptions = SqlBulkCopyOptions.TableLock;
                            // options.TemporaryTableInsertBatchSize = 10000;
                            options.BatchSize = 1000;
                            options.ColumnPrimaryKeyExpression = c => new { c.GUID };
                        });

We are implementing a generic approach and using GUID as the Key. We don't have an Id column in the data class/entity. This takes over 12 minutes to process the same 20000 records or sometimes just hangs.  I tried with different BatchSize and SqlBulckCopy options but not much improvement. 

Is there an issue with the way it is working ?

**Comment by JonathanMagnan** [comment]
Hello @keerthankumarCSnet ,

Could you provide us your table definition (info@zzzprojects.com), we will try your scenario on our side.

Perhaps we will also find something that could explain why it's so long.

Best Regards,

Jonathan

**Comment by keerthankumarCSnet** [comment]
Hi Jonathan,

Please find the table definition below, which get created based on the POCO:

  [Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //public int Id { get; set; }
        public Guid GUID { get; set; }
        public Guid ActivityGUID { get; set; }
        public Guid? ClientGUID { get; set; }
        public Guid UserGUID { get; set; }
        public string AuditEvent { get; set; }
        public string Notes { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }

If we set “Id” column as the Key and use BulkOperation.BulkInsert() method the performance is far better than using context.BulkInsert<T> and “GUID” as the Primary Key column. Look forward to hearing from you.

Thanks,
Keerthan

**Comment by JonathanMagnan** [comment]
Hello @keerthankumarCSnet ,

I'm very sorry, we forget to answer your question.

One way to improve the performance is to make sure `SqlBulkCopy` is directly used under the hood by our library. If you have some Identity column, you will need to use `AutoMapOutputDirection = false` to improve the performance.

You can use SQL Profiler to make sure `SqlBulkCopy` is used. Our library uses it whenever it can but in some scenario when the identity value must be outputted, a new strategy is used instead.

For example:

```csharp
context.BulkInsert(result, options =>
{
	options.AutoMapOutputDirection = false;
	options.SqlBulkCopyOptions = SqlBulkCopyOptions.TableLock;
});
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @keerthankumarCSnet ,

This issue will be closed since it has been answered (a little bit too late).

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
