### ISSUE TITLE
Computed Column Mapping for BulkInsert

### ISSUE THREAD

**Issue by HClausing** [zzzprojects/Bulk-Operations#2]
Could you help me with How to Map a Computed Column?

I'm getting exception on BulkInsert.

Thanks.

**Comment by zzzprojects** [comment]
Hello @HClausing ,

If you want to map a computed column, I would assume you want to output the value?

Here is an example how to output value:
```csharp
bulkOperation.ColumnMappings.Add("ComputedColumn", ColumnMappingDirectionType.Output);
```

If that's not what you are looking for, please provide me more information about what you want to achieve and/or the exception you receive.

Best Regards,

Jonathan

**Comment by HClausing** [comment]
Hello,

Thank you for the quick answer.

I have a computed column called "ClientToken" with SQL Formula [ID]+[Name], but no need the output value. I'm just using BulkInsert, and get theException. Maybe the raw sql is generating value for this column on INSERT, I believe.

Best Regards,

Henrique Clausing

**Comment by zzzprojects** [comment]
Are you using AutoMapping (not specifying any column)?

If yes, to solve this , issue, you will have to map every column but this one.

You can also use the "NotMapped"  attribute on field/property you don't want to automap.

Let me know if this solution worked or it's something else.

Best Regards,

Jonathan

**Comment by HClausing** [comment]
It's working now!!

Yes, I'm using AutoMap, but after .BulkInsert command, I have added one instance of ColumnMapping with .Identity = True and fixed the problem!!

Thank you so much. This is an excelent library for Bulk Operations. 100k of rows  on a large table (50 columns) done on a few minutes. Congratulations!

Best Regards,

Henrique Clausing

**Comment by zzzprojects** [comment]
That's great ;)

Make sure to join our [newsletter](http://zzzprojects.us9.list-manage.com/subscribe?u=cecbc4775cf67bf1ff82018af&id=4765ffa5f8)

We are currently re-writing our library from scratch and soon we will ask all your help for the new API design && feature.

Best Regards,

Jonathan
