### ISSUE TITLE
How to use BulkOperation.ResolutionType enum?

### ISSUE THREAD

**Issue by AndreaA86** [zzzprojects/Bulk-Operations#25]
Hi,
I am using the BulkOperation class (Z.BulkOperations namespace) but I didn't find found into the Wiki or into the assembly file the documentation about the ResolutionType enum.
I would understand the difference between the following enum values (how they work in detail) and the advantages/disadvantages to know what is the best solution for my cases:
1. Smart
2. TemporaryTable
3. WorkingTable

Thanks.
Andrea

**Comment by JonathanMagnan** [comment]
Hello AndraA86,

You should honestly don't use this option. It's more a debug options that help us to diagnostics issue.

In summary, for SQL Server:

- Smart: Will choose between `TemporaryTable` and `WorkingTable` depending on options & number of rows
- TemporaryTable: When you have more than 10 rows, a temporary table will be created, a SqlBulkCopy will be performed in this temporary table and an operation will be performed from the temporary table to the destination table.
- WorkingTable: A derived table will be used (a `SELECT UNION` with all values in parameters)

You can change the number of rows before the `TemporaryTable` Resolution is used with the `TemporaryTableMinRecord` option but be careful, SQL Server is limited by 2100 parameters. See: http://bulk-operations.net/temporary-table

Let me know if that answer successfully to your question.

Best Regards,

Jonathan

**Comment by AndreaA86** [comment]
Ok.

**Comment by AndreaA86** [comment]
A question about "TemporaryTable" enum value.
In SQLServer case the TemporaryTable option means that zBulk are using a tempdb permanent table or a global/local temporary table?

I ask this because in case I use a permanent tempdb I should also have the db privileges of creating tables as user. While with the temporary no.

Thanks.

**Comment by JonathanMagnan** [comment]
By default, it uses a temporary table, so `tempdb`.

However, there are a very few options that can affect it. For example, if you use `Always Encrypted Column`, a local table is required because of the certificate.

You can easily check it by looking at the `profiler` but it should use `tempdb` in your case.
