### ISSUE TITLE
EFCore - Owned types supported?

### ISSUE THREAD

**Issue by SimplerSoftware** [zzzprojects/Bulk-Operations#39]
Does this work with EFCore "owned" types?  Both with table splitting or when they are in a separate table?  For more info see here: [https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)

**Comment by JonathanMagnan** [comment]
Hello @SimplerSoftware ,

I'm very sorry for the late answer, it seems we forget to answer you.

Yes, `Entity Framework Extensions` (https://entityframework-extensions.net/) work with `owned types`.

You can also use directly the Bulk Operations library by specifying the right mapping.

Let me know if that answered to your question.

Best Regards,

Jonathan

**Comment by SimplerSoftware** [comment]
Thanks for confirming that.  I'll give it a try to see if it behaves the way we would expect it to. Thanks!
