### ISSUE TITLE
usage of composite automapkeynames

### ISSUE THREAD

**Issue by sagsgr8** [zzzprojects/Bulk-Operations#44]
Hi,
 
We require to use the multiple key mapping (How to assign multiple/group of automapkeyname) in bulk merge operation. 

We want to check multiple combination of columns to validate while uploading data. If record exist then it should check for combination of multiple columns & then update the existing record.

**Comment by JonathanMagnan** [comment]
Hello @sagsgr8 ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @sagsgr8 ,

It's possible to use a composite key by separating each column with a semicolon

```csharp
operation.AutoMapKeyName = "ColumnIntTest;ColumnStringTest";
```

However, I'm not sure that's what you are looking for.

Are you asking to be able to provide multiple key combinations?

For example:
- Check ID
- Check Code + Email
- Etc.

And the join clause will look something like this:

```sql
ON DestinationTable.ID = StagingTable.ID
OR (DestinationTable.Code = StagingTable.Code AND DestinationTable.Email = StagingTable.Email)
```

**Comment by korn3l** [comment]
`operation.AutoMapKeyName = "ColumnIntTest;ColumnStringTest";
`
This should be in the documentation.
