### ISSUE TITLE
BulkInsert with DataRowState.Added and AutoMapOutputIdentity fails

### ISSUE THREAD

**Issue by ulfrudalv** [zzzprojects/Bulk-Operations#48]
I'm trying to use BulkInsert to only insert added rows in a DataTable together with AutoMapOutputIdentity. It throws a NullReferenceException which does not say anything anout the problem. If I skip the DataRowState parameter then it works.
It is easy to reproduce by changing the call to BulkInsert in https://dotnetfiddle.net/g5pSS1 (row 40) to include DataRowState.Added.

**Comment by JonathanMagnan** [comment]
Hello @ulfrudalv ,

Thank you for reporting,

We will look at this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ulfrudalv ,

The v2.15.8 has been released.

This issue should now be fixed in this new version, a null check was missed when using our library with `DataRowState`.

Let me know if everything works as expected.

**Comment by ulfrudalv** [comment]
Hello Jonathan
Thank you for quick feedback! That solved my problem.

Best Regards
Ulf
