### ISSUE TITLE
Issue in BulkInsert function when System Cryptography: Use FIPS Compliant Algorithms for encryption, hashing and signing is Enabled the server.

### ISSUE THREAD

**Issue by manojahiraw** [zzzprojects/Bulk-Operations#55]
Hi Support,

When we use BulkInsert function we are getting following error. This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

System Cryptography: Use FIPS Compliant Algorithms for encryption, hashing and signing is Enabled the server. When we set FIPS Compliance security setting to Disabled it is working fine.

Do you have dll which can work with System Cryptography: Use FIPS Compliant Algorithms for encryption, hashing and signing is Enabled the server ?

Error Message: Exception has been thrown by the target of an invocation.
Stack Trace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at .(String )
   at .(String , String , Int32& )
   at .(ProviderType , Boolean , Boolean , Boolean )
   at Z.BulkOperations.BulkOperation.()
Inner Error Message: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
Inner Stack Trace:    at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()

Regards,
Manoj Ahir

**Comment by JonathanMagnan** [comment]
Hello @manojahiraw ,

It looks that we missed your issue.

That's normally not the error we are expected but we have indeed a license that supports FIPS

It's probably already done, but just contact our support service: info@zzzprojects.com and we will provide you one.

Best Regards,

Jon
