### ISSUE TITLE
Retrieving IDs of inserted records

### ISSUE THREAD

**Issue by AlwaysVbNet** [zzzprojects/Bulk-Operations#58]
After doing a bulk.BulkInsert(t) I would like to retrieve the IDs of the inserted records. At the moment I am able to get the RowsAffectedInserted only. 

Any ideas?

**Comment by JonathanMagnan** [comment]
Hello @AlwaysVbNet ,

If you use the `automapping`, you need to set the `AutoMapOutputIdentity = true`: https://dotnetfiddle.net/ICZEez

If you explicitly set your mapping, you need to set the `ColumnMappingDirectionType.Output`: https://dotnetfiddle.net/Jw6x2c

The library will automatically populate your entity or datatable identity.

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by AlwaysVbNet** [comment]
AutoMapOutputIdentity = true worked!
