### ISSUE TITLE
Getting Error "one of the identified items was in an invalid format" for BulkInsert

### ISSUE THREAD

**Issue by kushagrakasbi** [zzzprojects/Bulk-Operations#6]
So basically this is a very small issue but I have tried almost all sorts of modification. I Comapred the DB data types to the one in the codes too, etc etc. 
Now here is the piece of code which I am using for BulkInsert. I have changed the original table in which I wanted to bulk insert initially with a easier one for testing purpose. It just has three fields one datetime and two string columns

it basically throws the error mentioned in the title. I have tried using ColumnDirectionMapping to input and also tried changing the way I am inputting date in the DAY column. Any sort of suggestion would be helpful. 

Update : From my further research I guess the way I am assigning the date to the DAY column is wrong. Please suggest me a proper way of doing that.

**Comment by JonathanMagnan** [comment]
Hello @kushagrakasbi ,

Thank you for reporting this issue.

Can you confirm under which provider you are testing?

It seems to be an error under Oracle.

We will make some test today and give you an update shortly.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kushagrakasbi ,

We successfully reproduced this issue under Oracle. Most of the time, this issue is due by not providing a type in the DataSource.

The default type is a string which cannot be converted to a DateTime.

By example,

```csharp
var dt = new DataTable();
// dt.Columns.Add("COLUMNDATE"); // WILL NOT WORK
dt.Columns.Add("COLUMNDATE", typeof(DateTime)); // WORK

for (int i = 0; i < 5; i++)
{
    dt.Rows.Add(DateTime.Now);
}

// ...code...
operation.BulkInsert(dt);
```

Can you verify the DataSource type?

Let us know if you successfully fixed this issue or if you need more assistance.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kushagrakasbi ,

Looking at the example before the edited comment, I can confirm you the issue is exactly this ;)

The type when creating DataTable column must be specified.

Best Regards,

Jonathan

**Comment by kushagrakasbi** [comment]
Hey! @JonathanMagnan 
Thanks for such quick response. I guess that must be the issue. I'll test it out today and get back to you with the result. 

Regards,
Kushagra

**Comment by kushagrakasbi** [comment]
Hi @JonathanMagnan ,
I was successfully able to use BulkInsert after specifying the types while creating DataTable :)
Thanks a lot! I will contact you further if I have any more issues. 

Closing the issue.

Regards,
Kushagra
