### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by Nellymandela** [zzzprojects/Bulk-Operations#60]
Hello there,
Please I want to achieve a scenario,
We have an MVC Web application already built using EF and MSSQL DB.
The application and Database are both hosted on a local computer (COMPUTER A).
Also, we have a database with similar schema hosted on another computer (COMPUTER B) with access to internet.
We intend to provide access to the internet for this computer (COMPUTER A) so it can send its data to COMPUTER B while keeping track of synced data.
Do you think this project will do this?
Thanks.

**Comment by JonathanMagnan** [comment]
Hello @Nellymandela ,

Our library has a `sync` method, so yes it can maybe do it but it really depends on what level of synchronization you need. It works great if you don't need real-time synchronization, but for real-time, I believe SQL Server provides some better solution.

Let me know if that answers correctly to your question.

Best Regards,

Jon
