### ISSUE TITLE
Strip Characters from Text column

### ISSUE THREAD

**Issue by jennifer-bitwerx** [zzzprojects/Bulk-Operations#70]
I am working with a Bulk insert to load data from a legacy system into a postgres db.  The file format has null terminated strings which postgres does not support.  Error message from postgres is "ERROR: invalid byte sequence for encoding “UTF8”: 0x00"

I need to strip the null bytes from the text during the bulk insert. 
I have been attempting to accomplish this with the source value factor, but have had no luck. 
Do you have any suggestions?

Bulk operation Code: 

```csharp
using (var bulk = new BulkOperation(conn))
{
	try
	{
		bulk.Connection = conn;
		bulk.AutoMap = AutoMapType.ByName;
		bulk.BatchSize = 10000;
		bulk.BatchTimeout = 360;
		bulk.Provider = ProviderType.PostgreSql;
		bulk.DestinationSchemaName = "public";
		bulk.DestinationTableName = tableName.ToLower();
		bulk.CaseSensitive = CaseSensitiveType.DestinationInsensitive;
		bulk.ColumnMappings = BuildColumnMapping(columns);
		bulk.AutoTruncate = true;
		bulk.DataSource = dataReader;
		bulk.UseLogDump = true;
		bulk.LogDump = sb;

		bulk.BulkInsert();


		lbMessages.Items.Add("Insert Data Completed Successfully for Table: " + tableName);
	}
	catch (SqlException ex)
	{
		lbMessages.Items.Add($"LogDump:{sb.ToString()}");
		lbMessages.Items.Add("SQL Exception:" + ex.Message + ", Stack Trace:" + ex.StackTrace);
	}
	catch (Exception ex2)
	{
		lbMessages.Items.Add($"LogDump:{sb.ToString()}");
		lbMessages.Items.Add("Exception:" + ex2.Message + ", Stack Trace:" + ex2.StackTrace);
	}
	conn.Close();
	conn.Dispose();

}
```

Build Column mapping

```csharp
	if(dataType == typeof(System.String))
	{
		colMap = new ColumnMapping();
		colMap.SourceName = columName.ToString();
		colMap.DestinationName = columName.ToString();
		colMap.SourceValueFactory = x => {
			var r = (IDataReader)x;
			var stringValue = r.GetString(r.GetOrdinal($"{columName}"));
			var value = stringValue.Replace(Convert.ToChar(0x00).ToString(), string.Empty).Replace('\u0000'.ToString(), "");
			return value;
		};
	}
	else
	{

		colMap = new ColumnMapping();
		colMap.SourceName = columName.ToString();
		colMap.DestinationName = columName.ToString();
		colMap.DefaultValueResolution = DefaultValueResolutionType.Null;

	}
	mappings.Add(colMap);
}
```

**Comment by JonathanMagnan** [comment]
Hello @jennifer-bitwerx ,

My suggestion would probably have been exactly/similar to what you did.

At this point, you specify yourself the value so this `0x00` should no longer be part of the value you insert.

Is it possible for you to provide a runnable project with the minimum code to reproduces the issue? We will not be able to reproduce it otherwise since your fix should work so there is something else that's currently missing which we are not aware.

If you wish, you can send the project in private here: info@zzzprojects.com

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jennifer-bitwerx ,

Since our last conversation, we haven't heard from you!

Don't hesitate to provide a runnable project with the minimum code to reproduces the issue in private info@zzzprojects.com.

Looking forward to hearing from you,

Jon

**Comment by jennifer-bitwerx** [comment]
Hi!
Sorry for the delay, I’m trying to trim out some code to send a sample in.  In the meantime,  I tested the same code going to sql server rather than postgres and did have success with that.  Unfortunately that is not an acceptable solution.

Thanks
Jennifer

**Comment by JonathanMagnan** [comment]
No problem, take your time.

As soon as we will get your code we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jennifer-bitwerx ,

This issue will be closed since we haven't heard back from you.

However, don't hesitate to contact us once you'll be able to provide more information.

Best Regards,

Jon
