### ISSUE TITLE
When Insert/Update bulk data, columns not included who has default value in SQL

### ISSUE THREAD

**Issue by SinanBarut26** [zzzprojects/Bulk-Operations#71]
Example table

TblExample
{
ID INT NOT NULL
UserName VARCHAR(50) NULL
IsActive SMALLINT CONSTRAINT [DF_TblScanQueue_QueueStatus] DEFAULT ((0)) NOT NULL
}

_IsActive set from Constrains by default._

When I send bulk insert to this table and watch on sql profiler. I did't see IsActive field on execute bulk operation

System Info:
SQL Server 15.0
.Net Core 3.1
Z.EntityFramework.Extensions.EFCore 3.13.4

**Comment by JonathanMagnan** [comment]
Hello again, 

Since our last conversation, we haven't heard from you. 

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @SinanBarut26 ,

A simple reminder that we are here to assist you. 

Let me know if the solution provided worked for you. 

Dont hesitate to contact us for more information. 

Best regards, 

Jon

**Comment by SinanBarut26** [comment]
Sorry for the late response. 
It works for me. Thank you for your help.
