### ISSUE TITLE
Snowflake database support

### ISSUE THREAD

**Issue by fretep** [zzzprojects/Bulk-Operations#76]
I'm receiving the following error when executing against a `Snowflake.Data.Client.SnowflakeDbConnection`. I realize Snowflake isn't currently listed as a supported database in your documentation. Is there any way to work around this, or are there any plans to support Snowflake in the future?

```
Exception thrown: 'System.Exception' in Z.EntityFramework.Extensions.EFCore.dll: 'The Provider could not be resolved. You must explicitly set the Provider.'
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
```

**Comment by JonathanMagnan** [comment]
Hello @fretep ,

Unfortunately `Snowflake` is currently not supported as you noticed. There is currently no plan to support it either as we are focusing on some other features.

We might eventually change our mind but in the short term, we currently have more requests than we can handle.

Best Regards,

Jon
