### ISSUE TITLE
Source is Empty?

### ISSUE THREAD

**Issue by crmmvio** [zzzprojects/Bulk-Operations#9]
The code source is private?

**Comment by JonathanMagnan** [comment]
Hello @crmmvio ,

Yes, the source is kept in a private GitHub repository.

We might in the future release some source (The public API), however, the core must stay private for intellectual property.

Let me know if I answered correctly to your question.

Best Regards,

Jonathan

**Comment by crmmvio** [comment]
Ok, I understand.

Can I suggest you add a message stating this

thanks for your answer
Cleber

**Comment by JonathanMagnan** [comment]
Thank you @crmmvio  for this idea,

This is a great recommendation.

We added a readme.txt under the src directory.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: A readme.txt has been added and soon a example projects
